01_ButterfliesShop/ButterfliesShop/Models/Butterfly.cs
using ButterfliesShop.Validators;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ButterfliesShop.Models
{
    public class Butterfly
    {
        public int Id { get; set; }
        [DisplayName("Common Name:")]
        [Required(ErrorMessage = "Please enter the butterfly name")]
        public string CommonName { get; set; }
        [DisplayName("Butterfly Family:")]
        [Required(ErrorMessage = "Please select the butterfly family")]
        public Family? ButterflyFamily { get; set; }
        [DisplayName("Butterflies Quantity:")]
        [Required(ErrorMessage = "Please select the butterfly quantity")]
        [MaxButterflyQuantityValidation(50)]
        public int? Quantity { get; set; }
        [DisplayName("Characteristics: ")]
        [Required(ErrorMessage = "Please type the characteristics")]
        [StringLength(50)]
        public string Characteristics { get; set; }
        [DisplayName("Updated on")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yy}")]
        public DateTime CreatedDate { get; set; }
        [DisplayName("Butterflies Picture:")]
        [Required(ErrorMessage = "Please select the butterflies picture")]
        public IFormFile PhotoAvatar { get; set; }
        public string ImageName { get; set; }
        public byte[] PhotoFile { get; set; }
        public string ImageMimeType { get; set; }
    }
}

01_ButterfliesShop/ButterfliesShop/Models/Family.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ButterfliesShop.Models
{
    public enum Family
    {
        Grassland,
        Nymphalidae,
        Danaine,
        Riodinidae
    }
}

01_ButterfliesShop/ButterfliesShop/Models/IndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ButterfliesShop.Models
{
    public class IndexViewModel
    {
        public List<Butterfly> Butterflies { get; set; }
    }
}

01_ButterfliesShop/ButterfliesShop/Controllers/ButterflyController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ButterfliesShop.Models;
using ButterfliesShop.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

namespace ButterfliesShop.Controllers
{
    public class ButterflyController : Controller
    {
        private IDataService _data;
        private IHostingEnvironment _environment;
        private IButterfliesQuantityService _butterfliesQuantityService;

        public ButterflyController(IDataService data, IHostingEnvironment environment, IButterfliesQuantityService butterfliesQuantityService)
        {
            _data = data;
            _environment = environment;
            _butterfliesQuantityService = butterfliesQuantityService;
            InitializeButterfliesData();
        }

        private void InitializeButterfliesData()
        {
            if (_data.ButterfliesList == null)
            {
                List<Butterfly> butterflies = _data.ButterfliesInitializeData();
                foreach (var butterfly in butterflies)
                {
                    _butterfliesQuantityService.AddButterfliesQuantityData(butterfly);
                }
            }
        }

        public IActionResult GetImage(int id)
        {
            Butterfly requestedButterfly = _data.GetButterflyById(id);
            if (requestedButterfly != null)
            {
                string webRootpath = _environment.WebRootPath;
                string folderPath = @"\images\";
                string fullPath = webRootpath + folderPath + requestedButterfly.ImageName;

                if (System.IO.File.Exists(fullPath))
                {
                    var fileOnDisk = new FileStream(fullPath, FileMode.Open);
                    byte[] fileBytes;
                    using (var br = new BinaryReader(fileOnDisk))
                    {
                        fileBytes = br.ReadBytes((int)fileOnDisk.Length);
                    }
                    return File(fileBytes, requestedButterfly.ImageMimeType);
                }
                else if(requestedButterfly.PhotoFile.Length > 0)
                {
                    return File(requestedButterfly.PhotoFile, requestedButterfly.ImageMimeType);
                }
            }
            return NotFound();
        }

        public IActionResult Index()
        {
            var indexViewModel = new IndexViewModel();
            indexViewModel.Butterflies = _data.ButterfliesList;
            return View(indexViewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Butterfly butterfly)
        {
            if (!ModelState.IsValid)
            {
                return View(butterfly);
            }

            Butterfly lastButterfly = _data.ButterfliesList.LastOrDefault();
            butterfly.CreatedDate = DateTime.Today;

            if(butterfly.PhotoAvatar != null && butterfly.PhotoAvatar.Length > 0)
            {
                butterfly.ImageMimeType = butterfly.PhotoAvatar.ContentType;
                butterfly.ImageName = Path.GetFileName(butterfly.PhotoAvatar.FileName);
                butterfly.Id = lastButterfly.Id + 1;

                _butterfliesQuantityService.AddButterfliesQuantityData(butterfly);

                using (var memoryStream = new MemoryStream())
                {
                    butterfly.PhotoAvatar.CopyTo(memoryStream);
                    butterfly.PhotoFile = memoryStream.ToArray();
                }

                _data.AddButterfly(butterfly);

                return RedirectToAction("Index");
            }

            return View(butterfly);
        }

    }
}

01_ButterfliesShop/ButterfliesShop/Views/Butterfly/Create.cshtml
@using ButterfliesShop.Models
@model  Butterfly
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <link type="text/css" rel="stylesheet" href="~/css/butterflies-shop-styles.css" />
</head>
<body>
    <div class="container">
        <h1 class="main-title">
            Add Butterflies to the Shop
        </h1>
        <form enctype="multipart/form-data" method="post" asp-action="Create">
            <div asp-validation-summary="All"></div>
            <div class="form-field">
                <label asp-for="CommonName"></label>
                <input asp-for="CommonName" />
                <span asp-validation-for="CommonName"></span>
            </div>
            <div class="form-field">
                <label asp-for="ButterflyFamily"></label>
                <select asp-for="ButterflyFamily" asp-items="Html.GetEnumSelectList<Family>()">
                    <option value="" selected>Select</option>
                </select>
                <span asp-validation-for="ButterflyFamily"></span>
            </div>
            <div class="form-field">
                <label asp-for="Characteristics"></label>
                <textarea asp-for="Characteristics"></textarea>
                <span asp-validation-for="Characteristics"></span>
            </div>
            <div class="form-field">
                <label asp-for="Quantity"></label>
                <input asp-for="Quantity" />
                <span asp-validation-for="Quantity"></span>
            </div>
            <div class="form-field">
                <label asp-for="PhotoAvatar"></label>
                <input asp-for="PhotoAvatar" />
                <span asp-validation-for="PhotoAvatar"></span>
            </div>
            <div class="form-field">
                <input type="submit" value="Submit" />
            </div>
        </form>
    </div>
</body>
</html>

01_ButterfliesShop/ButterfliesShop/Views/Butterfly/Index.cshtml
@model ButterfliesShop.Models.IndexViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link type="text/css" rel="stylesheet" href="~/css/butterflies-shop-styles.css" />
</head>
<body>
    <div class="container">
        <h1 class="main-title">Butterflies Shop</h1>
        <p class="into">
            Welcome to our Web Store, Enjoy a Wide Variety of Butterflies
        </p>
        <p class="into">
            Our Butterflies in the Shop
        </p>
        <button onclick="location.href='@Url.Action("Create", "Butterfly")'">Add Butterflies</button>
        <div class="img-container">
            @foreach (var item in Model.Butterflies)
            {
                @*<div class="photo-index-card">
                    <p>@item.CommonName</p>
                    <p>@item.ButterflyFamily</p>
                    <p>@item.Quantity</p>
                    <p>@item.CreatedDate</p>
                </div>*@

                <h3 class="display-picture-title">
                    @Html.DisplayFor(modelItem => item.CommonName)
                </h3>
                if(item.ImageName != null)
                {
                    <div class="photo-display">
                        <img class="photo-display-img" src="@Url.Action("GetImage", "Butterfly", new { Id = item.Id })"/>
                    </div>
                }
                <div>
                    <p class="display-label">
                        @Html.DisplayNameFor(model => item.ButterflyFamily)
                    </p>
                    <br />
                    <p class="display-field">
                        @Html.DisplayFor(model => item.ButterflyFamily)
                    </p>
                </div>
                <div class="display-info">
                    <p class="display-label">
                        @Html.DisplayNameFor(model => item.Characteristics)
                    </p>
                    <p class="display-field">
                        @Html.DisplayFor(model => item.ButterflyFamily)
                    </p>
                </div>
                <div>
                    <p class="display-label">
                        @Html.DisplayNameFor(model => item.Quantity)
                    </p>
                    <p class="display-field">
                        @Html.DisplayFor(model => item.Quantity)
                    </p>
                </div>
                <div>
                    <p class="display-label">
                        @Html.DisplayNameFor(model => item.CreatedDate)
                    </p>
                    <p class="display-field">
                        @Html.DisplayFor(model => item.CreatedDate)
                    </p>
                </div>
            }
        </div>
    </div>
</body>
</html>